"""
Classic story templates for LittleTales.
Pre-configured story scenarios with familiar characters.
Each template has a `locale` list to control which language users see it.
"""

STORY_TEMPLATES = [
    # ── 中国经典 / Chinese Classics ──
    {
        "id": "monkey_king_brave",
        "title": "Monkey King",
        "title_zh": "美猴王",
        "emoji": "🐵",
        "description": "Overcome fears with courage and wit",
        "description_zh": "学勇敢，克服恐惧",
        "characters": ["Sun Wukong (Monkey King)"],
        "character_descriptions": "Sun Wukong (孙悟空): The legendary Monkey King with 72 transformations, rides on clouds, wields a golden staff. Brave, mischievous, and fiercely loyal.",
        "suggested_type": "adventure",
        "category": "chinese",
        "locale": ["zh"],
    },
    {
        "id": "nezha_hero",
        "title": "Nezha",
        "title_zh": "哪吒",
        "emoji": "🔥",
        "description": "Fight for justice, protect the weak",
        "description_zh": "正义勇敢，保护弱小",
        "characters": ["Nezha"],
        "character_descriptions": "Nezha (哪吒): A brave young warrior who rides on Wind Fire Wheels and wields a fire-tipped spear. Hot-tempered but righteous, protects the weak.",
        "suggested_type": "adventure",
        "category": "chinese",
        "locale": ["zh"],
    },
    {
        "id": "mulan_courage",
        "title": "Mulan",
        "title_zh": "花木兰",
        "emoji": "⚔️",
        "description": "Courage comes in many forms",
        "description_zh": "勇气有很多种",
        "characters": ["Mulan"],
        "character_descriptions": "Mulan (花木兰): A brave young woman, courageous, loyal to family, and skilled. She proves that anyone can be a hero regardless of who they are.",
        "suggested_type": "adventure",
        "category": "fairy_tale",
        "locale": ["zh", "en"],
    },
    {
        "id": "chang_e_sleep",
        "title": "Chang'e",
        "title_zh": "嫦娥",
        "emoji": "🌙",
        "description": "A gentle bedtime lullaby",
        "description_zh": "温柔的睡前摇篮曲",
        "characters": ["Chang'e"],
        "character_descriptions": "Chang'e (嫦娥): The goddess of the moon who lives in a beautiful palace with a jade rabbit. She is graceful, kind, and gentle.",
        "suggested_type": "bedtime",
        "category": "chinese",
        "locale": ["zh"],
    },
    {
        "id": "nuwa_creation",
        "title": "Nüwa",
        "title_zh": "女娲",
        "emoji": "🌈",
        "description": "Creativity and caring for the world",
        "description_zh": "创造与关爱世界",
        "characters": ["Nüwa"],
        "character_descriptions": "Nüwa (女娲): The goddess who created humans from clay and mended the sky with colorful stones. She is wise, nurturing, and endlessly creative.",
        "suggested_type": "educational",
        "category": "chinese",
        "locale": ["zh"],
    },
    {
        "id": "gourd_brothers",
        "title": "Gourd Brothers",
        "title_zh": "葫芦兄弟",
        "emoji": "🫒",
        "description": "Teamwork and brotherhood",
        "description_zh": "团结合作，兄弟齐心",
        "characters": ["The Gourd Brothers"],
        "character_descriptions": "The Gourd Brothers (葫芦兄弟): Seven brothers born from magical gourds, each with a unique superpower — fire, water, strength, invisibility, etc. They work together to defeat evil.",
        "suggested_type": "adventure",
        "category": "chinese",
        "locale": ["zh"],
    },
    {
        "id": "jingwei_fills_sea",
        "title": "Jingwei",
        "title_zh": "精卫填海",
        "emoji": "🐦",
        "description": "Never give up, persistence wins",
        "description_zh": "永不放弃，坚持到底",
        "characters": ["Jingwei"],
        "character_descriptions": "Jingwei (精卫): A tiny but determined bird who carries pebbles and twigs to fill the vast sea, never giving up despite the impossible task. A symbol of perseverance.",
        "suggested_type": "educational",
        "category": "chinese",
        "locale": ["zh"],
    },

    # ── 童话故事 / Fairy Tales ──
    {
        "id": "snow_white_kindness",
        "title": "Snow White",
        "title_zh": "白雪公主",
        "emoji": "👸",
        "description": "Kindness wins every heart",
        "description_zh": "善良感动所有人",
        "characters": ["Snow White"],
        "character_descriptions": "Snow White (白雪公主): A kind princess with skin as white as snow. She is gentle, optimistic, and loves all woodland creatures.",
        "suggested_type": "emotional",
        "category": "fairy_tale",
        "locale": ["zh", "en"],
    },
    {
        "id": "rapunzel_dreams",
        "title": "Rapunzel",
        "title_zh": "长发公主",
        "emoji": "💇‍♀️",
        "description": "Dreams and creativity",
        "description_zh": "梦想与创造力",
        "characters": ["Rapunzel"],
        "character_descriptions": "Rapunzel (长发公主): A princess with long golden hair in a tower. She is creative, resourceful, and longs for adventure.",
        "suggested_type": "bedtime",
        "category": "fairy_tale",
        "locale": ["zh", "en"],
    },
    {
        "id": "cinderella",
        "title": "Cinderella",
        "title_zh": "灰姑娘",
        "emoji": "👠",
        "description": "Kindness and hope through hardship",
        "description_zh": "善良与希望",
        "characters": ["Cinderella"],
        "character_descriptions": "Cinderella (灰姑娘): A hardworking, humble, and kind girl who remains hopeful despite hardship. She is rewarded for her gentle heart.",
        "suggested_type": "emotional",
        "category": "fairy_tale",
        "locale": ["zh", "en"],
    },
    {
        "id": "little_red_hood",
        "title": "Little Red Riding Hood",
        "title_zh": "小红帽",
        "emoji": "🧣",
        "description": "Be brave and stay alert",
        "description_zh": "勇敢机智，提高警惕",
        "characters": ["Little Red Riding Hood"],
        "character_descriptions": "Little Red Riding Hood (小红帽): A brave girl wearing a red cape who goes on an adventure through the woods. Curious, kind, and resourceful.",
        "suggested_type": "adventure",
        "category": "fairy_tale",
        "locale": ["zh", "en"],
    },
    {
        "id": "peter_pan_adventure",
        "title": "Peter Pan",
        "title_zh": "彼得潘",
        "emoji": "🧚",
        "description": "Fly to a magical adventure",
        "description_zh": "飞向梦幻岛冒险",
        "characters": ["Peter Pan"],
        "character_descriptions": "Peter Pan (彼得·潘): A boy who never grows up, can fly, brave and playful, leads adventures in Neverland.",
        "suggested_type": "adventure",
        "category": "fairy_tale",
        "locale": ["zh", "en"],
    },
    {
        "id": "aladdin_wishes",
        "title": "Aladdin",
        "title_zh": "阿拉丁",
        "emoji": "🧞",
        "description": "Best wishes come from the heart",
        "description_zh": "最好的愿望来自内心",
        "characters": ["Aladdin", "Genie"],
        "character_descriptions": "Aladdin (阿拉丁): A kind-hearted, clever young man who discovers a magic lamp. Genie (灯神): A powerful but friendly magical being who grants wishes.",
        "suggested_type": "adventure",
        "category": "fairy_tale",
        "locale": ["zh", "en"],
    },
    {
        "id": "puss_boots_clever",
        "title": "Puss in Boots",
        "title_zh": "穿靴子的猫",
        "emoji": "🐱",
        "description": "Brains beat brawn",
        "description_zh": "智慧胜过蛮力",
        "characters": ["Puss in Boots"],
        "character_descriptions": "Puss in Boots (穿靴子的猫): A clever, swashbuckling cat who wears boots and a hat. Witty, resourceful, and fiercely loyal.",
        "suggested_type": "adventure",
        "category": "fairy_tale",
        "locale": ["zh", "en"],
    },
    {
        "id": "sleeping_beauty",
        "title": "Sleeping Beauty",
        "title_zh": "睡美人",
        "emoji": "💤",
        "description": "A magical bedtime dream",
        "description_zh": "一个奇妙的睡前故事",
        "characters": ["Sleeping Beauty"],
        "character_descriptions": "Sleeping Beauty (睡美人): A gentle princess who falls into a magical sleep. She is kind, graceful, and surrounded by a beautiful enchanted garden.",
        "suggested_type": "bedtime",
        "category": "fairy_tale",
        "locale": ["zh", "en"],
    },
    {
        "id": "jack_beanstalk",
        "title": "Jack & the Beanstalk",
        "title_zh": "杰克与魔豆",
        "emoji": "🌱",
        "description": "Courage and cleverness up high",
        "description_zh": "勇气与机智的冒险",
        "characters": ["Jack"],
        "character_descriptions": "Jack (杰克): A brave and resourceful boy who climbs a giant beanstalk into the clouds, faces a giant, and uses his wits to succeed.",
        "suggested_type": "adventure",
        "category": "fairy_tale",
        "locale": ["zh", "en"],
    },
    {
        "id": "pinocchio",
        "title": "Pinocchio",
        "title_zh": "匹诺曹",
        "emoji": "🤥",
        "description": "Honesty is the best policy",
        "description_zh": "诚实是最好的品质",
        "characters": ["Pinocchio"],
        "character_descriptions": "Pinocchio (匹诺曹): A wooden puppet who dreams of becoming a real boy. His nose grows when he lies. He learns that honesty, bravery, and kindness make a real person.",
        "suggested_type": "educational",
        "category": "fairy_tale",
        "locale": ["zh", "en"],
    },
    {
        "id": "alice_wonderland",
        "title": "Alice in Wonderland",
        "title_zh": "爱丽丝梦游仙境",
        "emoji": "🐇",
        "description": "A curious adventure in a strange land",
        "description_zh": "奇妙仙境里的冒险",
        "characters": ["Alice"],
        "character_descriptions": "Alice (爱丽丝): A curious and imaginative girl who falls down a rabbit hole into a fantastical world full of peculiar characters and nonsensical rules.",
        "suggested_type": "adventure",
        "category": "fairy_tale",
        "locale": ["zh", "en"],
    },
    {
        "id": "frog_prince",
        "title": "The Frog Prince",
        "title_zh": "青蛙王子",
        "emoji": "🐸",
        "description": "Don't judge by appearances",
        "description_zh": "不要以貌取人",
        "characters": ["The Frog Prince"],
        "character_descriptions": "The Frog Prince (青蛙王子): A prince cursed into a frog. He is patient, kind, and teaches that true beauty is on the inside.",
        "suggested_type": "emotional",
        "category": "fairy_tale",
        "locale": ["zh", "en"],
    },

    # ── 寓言传说 / Fables ──
    {
        "id": "three_pigs_effort",
        "title": "Three Little Pigs",
        "title_zh": "三只小猪",
        "emoji": "🐷",
        "description": "Do things right the first time",
        "description_zh": "认真做事才能做好",
        "characters": ["The Three Little Pigs"],
        "character_descriptions": "Three pig brothers who each build a house — one of straw, one of sticks, and one of bricks. They learn the value of hard work.",
        "suggested_type": "educational",
        "category": "fable",
        "locale": ["zh", "en"],
    },
    {
        "id": "tortoise_hare_steady",
        "title": "Tortoise & Hare",
        "title_zh": "龟兔赛跑",
        "emoji": "🐢",
        "description": "Slow and steady wins",
        "description_zh": "坚持到底就能赢",
        "characters": ["The Tortoise", "The Hare"],
        "character_descriptions": "The Tortoise (乌龟): Slow but steady and determined. The Hare (兔子): Fast but overconfident. Together they teach about perseverance and humility.",
        "suggested_type": "educational",
        "category": "fable",
        "locale": ["zh", "en"],
    },
    {
        "id": "three_bears_sharing",
        "title": "Three Bears",
        "title_zh": "三只小熊",
        "emoji": "🐻",
        "description": "Sharing and boundaries",
        "description_zh": "分享与尊重",
        "characters": ["The Three Bears"],
        "character_descriptions": "The Three Bears: Papa Bear (big and gentle), Mama Bear (warm and caring), and Baby Bear (small and playful). A loving bear family.",
        "suggested_type": "emotional",
        "category": "fable",
        "locale": ["zh", "en"],
    },
    {
        "id": "ugly_duckling_self",
        "title": "Ugly Duckling",
        "title_zh": "丑小鸭",
        "emoji": "🦢",
        "description": "Everyone is beautiful in their own way",
        "description_zh": "每个人都有独特的美",
        "characters": ["The Ugly Duckling"],
        "character_descriptions": "The Ugly Duckling (丑小鸭): A little bird who looks different from everyone else but eventually grows into a beautiful swan. A story about self-acceptance.",
        "suggested_type": "emotional",
        "category": "fable",
        "locale": ["zh", "en"],
    },
    {
        "id": "boy_who_cried_wolf",
        "title": "Boy Who Cried Wolf",
        "title_zh": "狼来了",
        "emoji": "🐺",
        "description": "Always tell the truth",
        "description_zh": "要诚实，不说谎",
        "characters": ["The Shepherd Boy"],
        "character_descriptions": "The Shepherd Boy (放羊娃): A young boy who learns the hard way that lying has consequences. When he tells the truth, nobody believes him.",
        "suggested_type": "educational",
        "category": "fable",
        "locale": ["zh", "en"],
    },
    {
        "id": "ant_grasshopper",
        "title": "Ant & Grasshopper",
        "title_zh": "蚂蚁和蚱蜢",
        "emoji": "🐜",
        "description": "Hard work pays off",
        "description_zh": "勤劳才有好收获",
        "characters": ["The Ant", "The Grasshopper"],
        "character_descriptions": "The Ant (蚂蚁): Hardworking and prepared. The Grasshopper (蚱蜢): Playful and carefree. Together they teach about planning ahead and responsibility.",
        "suggested_type": "educational",
        "category": "fable",
        "locale": ["zh", "en"],
    },
    {
        "id": "lion_mouse",
        "title": "Lion & Mouse",
        "title_zh": "狮子和老鼠",
        "emoji": "🦁",
        "description": "Even the small can help the great",
        "description_zh": "小小的也能帮大忙",
        "characters": ["The Lion", "The Mouse"],
        "character_descriptions": "The Lion (狮子): Strong and powerful. The Mouse (老鼠): Tiny but brave and grateful. Together they show that kindness is never wasted and everyone has value.",
        "suggested_type": "emotional",
        "category": "fable",
        "locale": ["zh", "en"],
    },
    {
        "id": "north_wind_sun",
        "title": "North Wind & Sun",
        "title_zh": "北风和太阳",
        "emoji": "☀️",
        "description": "Gentleness beats force",
        "description_zh": "温柔比强硬更有用",
        "characters": ["The North Wind", "The Sun"],
        "character_descriptions": "The North Wind (北风): Cold, forceful, and proud. The Sun (太阳): Warm, gentle, and patient. They compete to see who can make a traveler remove his coat.",
        "suggested_type": "educational",
        "category": "fable",
        "locale": ["zh", "en"],
    },

    # ── 经典联手 / Dream Team ──
    {
        "id": "monkey_nezha_team",
        "title": "Monkey King & Nezha",
        "title_zh": "美猴王和哪吒",
        "emoji": "💥",
        "description": "Two heroes team up",
        "description_zh": "两位英雄联手冒险",
        "characters": ["Sun Wukong", "Nezha"],
        "character_descriptions": "Sun Wukong (孙悟空): The Monkey King, 72 transformations, golden staff, rides clouds. Nezha (哪吒): Wind Fire Wheels, fire-tipped spear, righteous young warrior.",
        "suggested_type": "adventure",
        "category": "crossover",
        "locale": ["zh"],
    },
    {
        "id": "cinderella_red_friends",
        "title": "Cinderella & Red Riding Hood",
        "title_zh": "灰姑娘和小红帽",
        "emoji": "👗",
        "description": "Two heroines become friends",
        "description_zh": "两位女孩成为好朋友",
        "characters": ["Cinderella", "Little Red Riding Hood"],
        "character_descriptions": "Cinderella (灰姑娘): Hardworking, humble, kind and hopeful despite hardship. Little Red Riding Hood (小红帽): Brave girl in a red cape, curious and adventurous.",
        "suggested_type": "emotional",
        "category": "crossover",
        "locale": ["zh", "en"],
    },
    {
        "id": "alice_pinocchio_team",
        "title": "Alice & Pinocchio",
        "title_zh": "爱丽丝和匹诺曹",
        "emoji": "🎭",
        "description": "Curiosity meets honesty",
        "description_zh": "好奇心遇上诚实",
        "characters": ["Alice", "Pinocchio"],
        "character_descriptions": "Alice (爱丽丝): Curious and imaginative, explores wonderland. Pinocchio (匹诺曹): A puppet learning to be real through honesty and kindness.",
        "suggested_type": "adventure",
        "category": "crossover",
        "locale": ["zh", "en"],
    },
]

CATEGORY_LABELS = {
    "chinese": {"en": "Chinese Legends", "zh": "中国神话"},
    "fairy_tale": {"en": "Fairy Tales", "zh": "童话故事"},
    "fable": {"en": "Fables", "zh": "寓言故事"},
    "crossover": {"en": "Dream Team", "zh": "经典联手"},
}


def get_templates_by_category(locale=None):
    """Group templates by category for API response. Optionally filter by locale."""
    categories = {}
    for tpl in STORY_TEMPLATES:
        if locale and locale not in tpl.get("locale", []):
            continue
        cat = tpl["category"]
        if cat not in categories:
            categories[cat] = {
                "label": CATEGORY_LABELS.get(cat, {"en": cat, "zh": cat}),
                "templates": [],
            }
        categories[cat]["templates"].append(tpl)
    return categories


def get_template_by_id(template_id: str):
    """Find a template by ID."""
    for tpl in STORY_TEMPLATES:
        if tpl["id"] == template_id:
            return tpl
    return None


def get_character_descriptions(character_ids: list[str]) -> str:
    """Legacy support - build prompt-ready description from template IDs."""
    descriptions = []
    for cid in character_ids:
        tpl = get_template_by_id(cid)
        if tpl:
            descriptions.append(tpl["character_descriptions"])
    return "\n".join(descriptions)
