# Generated by Django 6.0.3 on 2026-04-04 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('personality', models.CharField(blank=True, choices=[('shy', 'Shy'), ('angry', 'Easily Angry'), ('afraid_dark', 'Afraid of Dark'), ('no_sleep', "Doesn't Want to Sleep"), ('no_share', "Doesn't Like Sharing"), ('picky_eater', 'Picky Eater'), ('anxious', 'Anxious'), ('stubborn', 'Stubborn'), ('other', 'Other')], max_length=20)),
                ('personality_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('moral', models.TextField(blank=True)),
                ('age_group', models.CharField(choices=[('3-5', '3-5 years'), ('5-7', '5-7 years')], max_length=5)),
                ('story_type', models.CharField(choices=[('bedtime', 'Bedtime'), ('adventure', 'Adventure'), ('educational', 'Educational'), ('emotional', 'Emotional')], max_length=20)),
                ('language', models.CharField(choices=[('zh', 'Chinese'), ('en', 'English'), ('bilingual', 'Bilingual')], default='zh', max_length=10)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('generation_params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='stories.childprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating_text', 'Generating Text'), ('generating_images', 'Generating Images'), ('generating_audio', 'Generating Audio'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='stories.story')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('image_prompt', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('narration', models.TextField(blank=True)),
                ('dialogue', models.JSONField(blank=True, default=list)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='stories.story')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('story', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='StoryAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_type', models.CharField(choices=[('narration', 'Narration'), ('character', 'Character Voice'), ('full_page', 'Full Page Mix')], max_length=20)),
                ('character_name', models.CharField(blank=True, max_length=100)),
                ('voice_id', models.CharField(blank=True, max_length=50)),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('duration_seconds', models.FloatField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='stories.storypage')),
            ],
            options={
                'ordering': ['page__page_number'],
            },
        ),
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('daily_stories_generated', models.PositiveIntegerField(default=0)),
                ('monthly_stories_generated', models.PositiveIntegerField(default=0)),
                ('last_daily_reset', models.DateField(auto_now_add=True)),
                ('last_monthly_reset', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
