# Generated by Django 6.0.3 on 2026-04-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_last_played_at_storyfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
