# Generated by Django 6.0.3 on 2026-04-07 02:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_remove_childprofile_age_childprofile_birth_date'),
        ('users', '0002_alter_contentapproval_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='allowed_story_types',
            field=models.JSONField(blank=True, default=list, help_text='Allowed story types, e.g. ["bedtime","educational"]. Empty = all allowed.'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='child_avatars/'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='bedtime',
            field=models.TimeField(blank=True, help_text="Bedtime for this child, e.g. 20:30. Stories won't play after this time.", null=True),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='blocked_story_types',
            field=models.JSONField(blank=True, default=list, help_text='Blocked story types, e.g. ["adventure"]. Takes precedence over allowed.'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='current_usage_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='daily_screen_limit_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Daily screen time limit in minutes'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_profiles', to='users.family'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='favorite_themes',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["dinosaurs", "space", "princesses", "animals"]'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='last_usage_reset_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='wake_time',
            field=models.TimeField(blank=True, help_text='Wake time for this child, e.g. 07:00.', null=True),
        ),
    ]
