# Generated by Django 6.0.3 on 2026-04-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_childprofile_allowed_story_types_childprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='personality',
            field=models.JSONField(blank=True, default=list, help_text='List of personality traits, e.g. ["shy", "anxious"]'),
        ),
    ]
