# Generated by Django 6.0.3 on 2026-04-07 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_alter_childprofile_personality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User-given name, e.g. 'Mommy Voice'", max_length=100)),
                ('speaker_id', models.CharField(help_text='Volcengine speaker_id', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('training', 'Training'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('demo_audio_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_voices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
