# Generated by Django 6.0.3 on 2026-04-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_customvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='gender',
            field=models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl')], default='boy', max_length=5),
        ),
    ]
