# Generated by Django 6.0.3 on 2026-04-07 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_childprofile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('total_stories_read', models.PositiveIntegerField(default=0)),
                ('total_reading_minutes', models.PositiveIntegerField(default=0)),
                ('last_read_date', models.DateField(blank=True, null=True)),
                ('monthly_reads', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
