# Generated by Django 6.0.3 on 2026-04-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_storycollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='character_positions',
            field=models.JSONField(blank=True, default=list, help_text='[{"name": "Char", "x": 30, "y": 50}] — head position as % of image'),
        ),
    ]
