# Generated by Django 6.0.3 on 2026-04-08 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_storypage_character_positions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(default=list, help_text='[{"question":"...", "choices":["A","B","C"], "answer":0, "emoji":"🌟"}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='stories.story')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=list, help_text='[0, 2, 1] — selected choice indices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.childprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='stories.storyquiz')),
            ],
        ),
    ]
