# Generated by Django 6.0.3 on 2026-04-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_storyquiz_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='coloring_image_url',
            field=models.URLField(blank=True, help_text='Line art version for coloring activity', max_length=500),
        ),
    ]
