# Generated by Django 6.0.3 on 2026-04-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_add_coloring_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='quiz_voice',
            field=models.CharField(blank=True, default='', help_text='TTS voice ID for reading quiz questions aloud, e.g. zh_female_xiaoxue_uranus_bigtts', max_length=100),
        ),
    ]
