# Generated by Django 6.0.3 on 2026-04-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_add_quiz_voice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='quiz_voice',
        ),
    ]
