# Generated by Django 6.0.3 on 2026-04-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_remove_quiz_voice_from_childprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='character_description',
            field=models.TextField(blank=True, help_text='AI-ready text description, e.g. "A young girl with short black hair, medium skin, round glasses"'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='character_features',
            field=models.JSONField(blank=True, default=dict, help_text='{"gender":"girl","skin_tone":"medium","hair_style":"short","hair_color":"black","extras":["glasses"]}'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='character_image_url',
            field=models.URLField(blank=True, help_text='AI-generated character reference image URL', max_length=500),
        ),
    ]
