# Generated by Django 6.0.3 on 2026-04-08 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_add_character_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='vocabulary',
            field=models.JSONField(blank=True, default=list, help_text='[{"word": "brave", "definition": "Not afraid to try new things", "emoji": "🦁"}]'),
        ),
        migrations.CreateModel(
            name='VocabularyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_reviews', to='stories.childprofile')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_reviews', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'child_profile', 'word', 'story')},
            },
        ),
    ]
