# Generated by Django 6.0.3 on 2026-04-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0016_add_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='share_code',
            field=models.CharField(blank=True, help_text='Unique code for public sharing link. Null = not shared.', max_length=12, null=True, unique=True),
        ),
    ]
