# Generated by Django 6.0.3 on 2026-04-10 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0017_story_share_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagequota',
            name='daily_characters_generated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usagequota',
            name='last_character_reset',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='usagequota',
            name='signup_bonus_remaining',
            field=models.PositiveIntegerField(default=5, help_text='Free trial credits given on signup'),
        ),
    ]
