# Generated by Django 6.0.3 on 2026-04-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0018_usagequota_daily_characters_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Visible on Discover page'),
        ),
        migrations.AddField(
            model_name='story',
            name='moderation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='moderation_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
