# Generated by Django 6.0.3 on 2026-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0019_add_discover_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='age_group',
            field=models.CharField(choices=[('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-7', '5-7 years'), ('8-10', '8-10 years'), ('11-12', '11-12 years')], max_length=5),
        ),
    ]
