# Generated by Django 6.0.3 on 2026-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0021_add_story_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='goodnight_message',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
