# Generated by Django 6.0.3 on 2026-04-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0022_add_goodnight_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='video_exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='R2 URL of exported MP4 if generated'),
        ),
    ]
