# Generated by Django 6.0.3 on 2026-04-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0024_vocabcollection_vocabcollectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='deferred_assets_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='State of the deferred coloring/vocab asset generation.', max_length=20),
        ),
    ]
