# Generated by Django 6.0.3 on 2026-04-04 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Family name (e.g., 'The Smiths')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='ChildActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('story_view', 'Viewed Story'), ('story_generate', 'Generated Story'), ('login', 'Logged In'), ('logout', 'Logged Out')], max_length=20)),
                ('content_type', models.CharField(blank=True, help_text='story, comic, etc.', max_length=10)),
                ('content_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_title', models.CharField(blank=True, max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Time spent in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_activities', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.family')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenTimeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit_minutes', models.PositiveIntegerField(default=30, help_text='Daily screen time limit in minutes')),
                ('current_usage_minutes', models.PositiveIntegerField(default=0, help_text='Current day usage in minutes')),
                ('last_reset_date', models.DateField(auto_now_add=True, help_text='Last date when usage was reset')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screen_time_limit', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_limits', to='users.family')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], default='parent', max_length=10)),
                ('age_group', models.CharField(blank=True, choices=[('0-2', 'Infants & Early Toddlers (0-2 years)'), ('2-4', 'Preschool (2-4 years)'), ('5-7', 'Early Elementary (5-7 years)'), ('8-10', 'Elementary (8-10 years)'), ('11-12', 'Tweens (11-12 years)'), ('13+', 'Teens (13+ years)')], max_length=10)),
                ('actual_age', models.PositiveIntegerField(blank=True, help_text="Child's actual age in years", null=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('favorite_themes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('story', 'Story')], max_length=10)),
                ('content_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('blocked', 'Blocked'), ('pending', 'Pending Review')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_content', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('parent', 'child', 'content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('daddy', 'Daddy'), ('mommy', 'Mommy'), ('grandpa', 'Grandpa'), ('grandma', 'Grandma'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('guardian', 'Guardian'), ('child', 'Child')], max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('pin_code', models.CharField(blank=True, help_text='PIN for switching back from child account', max_length=6)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('family', 'user')},
            },
        ),
    ]
