# Generated by Django 6.0.3 on 2026-04-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentapproval',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contentapproval',
            name='child',
        ),
        migrations.RemoveField(
            model_name='contentapproval',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='screentimelimit',
            name='child',
        ),
        migrations.RemoveField(
            model_name='screentimelimit',
            name='family',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='pin_code',
        ),
        migrations.AlterField(
            model_name='familymember',
            name='role',
            field=models.CharField(choices=[('daddy', 'Daddy'), ('mommy', 'Mommy'), ('grandpa', 'Grandpa'), ('grandma', 'Grandma'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('guardian', 'Guardian')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='actual_age',
            field=models.PositiveIntegerField(blank=True, help_text="User's actual age in years", null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('parent', 'Parent')], default='parent', max_length=10),
        ),
        migrations.DeleteModel(
            name='ChildActivity',
        ),
        migrations.DeleteModel(
            name='ContentApproval',
        ),
        migrations.DeleteModel(
            name='ScreenTimeLimit',
        ),
    ]
