# Generated by Django 6.0.3 on 2026-04-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_contentapproval_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='app_theme',
            field=models.CharField(choices=[('default', 'Starry Night (Default)'), ('ocean', 'Ocean Dream'), ('forest', 'Enchanted Forest'), ('candy', 'Candy Land'), ('sunset', 'Sunset Glow')], default='default', help_text='App color theme', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quiz_voice',
            field=models.CharField(blank=True, default='', help_text='TTS voice ID for reading quiz questions aloud', max_length=100),
        ),
    ]
