# Generated by Django 6.0.3 on 2026-04-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_familyinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='app_theme',
            field=models.CharField(choices=[('default', 'Storybook (Default)'), ('nightsky', 'Night Sky')], default='default', help_text='App color theme', max_length=20),
        ),
    ]
