# Generated by Django 6.0.3 on 2026-04-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_update_theme_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='parental_pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
