# Generated by Django 6.0.3 on 2026-04-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_parental_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_narrator_voice',
            field=models.CharField(blank=True, default='', help_text='Default TTS voice for new story narration', max_length=100),
        ),
    ]
