# Generated by Django 6.0.3 on 2026-04-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_default_narrator_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='word_card_voice',
            field=models.CharField(blank=True, default='', help_text='TTS voice for vocabulary word card playback (Listen / Play All)', max_length=100),
        ),
    ]
